name = "strivetrack-media-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Bind the existing R2 bucket by name
[[r2_buckets]]
binding = "R2"           # available in code as env.R2
bucket_name = "strivetrack-media"

[vars]
# Configure these via wrangler secret put in production
# ADMIN_EMAIL will be used to grant full admin access
# JWT_SECRET is used to validate pure Cloudflare JWT tokens
# ADMIN_EMAIL = "iamhollywoodpro@protonmail.com"
